# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('did', models.CharField(max_length=10)),
                ('ddep', models.CharField(max_length=30)),
                ('demail', models.CharField(max_length=10)),
                ('dpass', models.CharField(max_length=30)),
                ('dpassre', models.CharField(max_length=30)),
            ],
        ),
    ]
