# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-21 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_drreg_dimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drreg',
            name='dimage',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
