# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20240221_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='drreg',
            name='dphn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drreg',
            name='demail',
            field=models.CharField(max_length=100),
        ),
    ]
