# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-29 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20240222_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='breg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=10)),
                ('phno', models.IntegerField()),
                ('dname', models.CharField(max_length=30)),
                ('did', models.CharField(max_length=30)),
                ('dphn', models.IntegerField()),
                ('bdate', models.DateField()),
            ],
        ),
    ]
