# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-29 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_breg'),
    ]

    operations = [
        migrations.AddField(
            model_name='breg',
            name='ddep',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
