# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-01 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_breg_ddep'),
    ]

    operations = [
        migrations.CreateModel(
            name='lreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
            ],
        ),
    ]
