# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-01 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_lreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lreg',
            old_name='name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='lreg',
            old_name='passw',
            new_name='lpass',
        ),
    ]
