# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20240301_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('reject', 'REJECTED')], default='pending', max_length=30),
        ),
    ]
