# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-03-01 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20240301_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='status',
        ),
        migrations.AddField(
            model_name='breg',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=30),
        ),
    ]
