# Generated by Django 4.0.1 on 2024-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20240301_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=30),
        ),
    ]
