# Generated by Django 4.0.1 on 2024-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_labservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labservice',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
