# Generated by Django 4.0.1 on 2024-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_labservice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='breg',
            name='fee',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
