# Generated by Django 4.0.1 on 2024-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_drreg_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=20)),
                ('did', models.CharField(max_length=30)),
                ('dphn', models.IntegerField()),
                ('ddep', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=30)),
            ],
        ),
    ]
