# Generated by Django 4.0.1 on 2024-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='dname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
