# Generated by Django 5.0.2 on 2024-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_pay_dname'),
    ]

    operations = [
        migrations.AddField(
            model_name='labservice',
            name='contact',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labservice',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
