# Generated by Django 5.0.2 on 2024-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_alter_breg_id_alter_drreg_id_alter_labservice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=10)),
                ('phno', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=100)),
                ('lbdate', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=30)),
            ],
        ),
    ]
