# Generated by Django 4.0.1 on 2024-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_labpay_remove_lbreg_amount_remove_lbreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbreg',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
