# Generated by Django 4.0.1 on 2024-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_lbreg_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labservice',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='lbreg',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='labpay',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
