# Generated by Django 4.0.1 on 2024-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_labpay_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='breg',
            name='btime',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
