# Generated by Django 4.2 on 2024-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_pay_priscription_alter_breg_id_alter_drreg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='bdate',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
