# Generated by Django 4.2 on 2024-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_pay_bdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpay',
            name='time',
        ),
        migrations.AddField(
            model_name='labservice',
            name='tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
