# Generated by Django 4.0.1 on 2024-03-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_remove_labpay_time_labservice_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbreg',
            name='tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
