# Generated by Django 5.1.5 on 2025-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_chatmessage_reg_email_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drreg',
            old_name='demail',
            new_name='email',
        ),
    ]
