# Generated by Django 5.1.5 on 2025-03-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_rename_demail_drreg_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breg',
            old_name='pid',
            new_name='email',
        ),
    ]
