# Generated by Django 5.1.5 on 2025-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_rename_pid_breg_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breg',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
